8 dao crud office
jadatix/carBooking pull request #11
Opened 2022-11-07 13:56 UTC by jadatix

Fixes #8

2022-11-07 15:47 UTC, seshotake requested changes

2022-11-07 15:47 UTC, seshotake commented on src/main/java/org/jadatix/carbooking/dao/OfficeDao.java
> +        Query theQuery = (Query) entityManager.createQuery(query, Office.class);
Why not use just strings concatenation?
```suggestion
        Query theQuery = (Query) entityManager.createQuery("from " + tableName, Office.class);
```

2022-11-07 15:47 UTC, seshotake commented on src/main/java/org/jadatix/carbooking/api/v1/offices/OfficeController.java
> +        HttpStatus status = responseOffice != null ? HttpStatus.OK : HttpStatus.BAD_REQUEST;
Isn't that always the true?

2022-11-07 19:16 UTC, seshotake requested changes

2022-11-07 19:16 UTC, seshotake commented on src/main/java/org/jadatix/carbooking/api/v1/offices/OfficeController.java
> +        return new ResponseEntity<>(null, HttpStatus.OK);
Should it return office?
```suggestion
    public void updateOffice(@PathVariable Long id, @RequestBody Office office) {
        officeService.updateOffice(office);
```

2022-11-07 19:16 UTC, seshotake commented on src/main/java/org/jadatix/carbooking/api/v1/offices/OfficeController.java
> +
Maybe, just use?

```suggestion
officeService.deleteOfficeById(id);
```

2022-11-07 19:16 UTC, seshotake commented on src/main/java/org/jadatix/carbooking/dao/OfficeDao.java
> +        Query theQuery = (Query) entityManager.createQuery(query, Office.class);
is it necessary cast `TypedQuery<T>` to `Query`?

https://docs.oracle.com/javaee/7/api/javax/persistence/EntityManager.html#createQuery-java.lang.String-java.lang.Class-

If you don't need `TypedQuery` just use `createNativeQuery`

https://docs.oracle.com/javaee/7/api/javax/persistence/EntityManager.html#createNativeQuery-java.lang.String-

2022-11-08 14:03 UTC, voltor commented on src/main/java/org/jadatix/carbooking/dao/OfficeDao.java
> +public class OfficeDao {
DAO isn't a Repository, here better to use `@Service` or `@Component`

2022-11-08 14:03 UTC, voltor commented on src/main/java/org/jadatix/carbooking/dao/OfficeDao.java
> +    private EntityManager entityManager;
Could you use here a Repository; more see SpringData

2022-11-09 15:26 UTC, merged